### PR TITLE
#36 - problem trying to use with gdrive: resolves escaping issues

### LINKED ISSUE #36: Problem trying to use with gdrive
First of all, nice project!

Im trying to use volume-syncing-controller with google drive type, but im getting error with token value.

```
PodFilesystemSync.yaml:
...
    env:
        REMOTE_TYPE: drive
        REMOTE_CLIENT_ID: xxx.apps.googleusercontent.com
        REMOTE_CLIENT_SECRET: GOCSPX-xxx
        REMOTE_TOKEN: '{"access_token":"xxx","token_type":"Bearer","refresh_token":"xxx","expiry":"2022-05-23T01:04:59.737000688Z"}'
        REMOTE_SCOPE: drive
...
```

And the output:

```
> kubectl logs -n internal -c volume-syncing-sidecar vaultwarden-59f586c868-zm7qk
Error: invalid argument "token = {\"access_token\":\"xxx\",\"token_type\":\"Bearer\",\"refresh_token\":\"xxx\",\"expiry\":\"2022-05-23T01:04:59.737000688Z\"}" for "-p, --param" flag: parse error on line 1, column 10: bare " in non-quoted-field
Usage:
  volume-syncing-controller sync-to-remote [flags]
  ....
```

Not sure if this a problem with rclone itself or volume-syncing-controller

### PR DESCRIPTION
**Pull request by blackandred**
This PR resolves an escaping issue.

Notice: Includes extra formatting changes

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -46,7 +47,7 @@ func appendVar(args []string, prefix string, switchName string, envName string,
 	name := strings.ToLower(namePair[1])
 
 	args = append(args, switchName)
-	args = append(args, name+" = "+value)
+	args = append(args, name+"="+value)
```
Comment (blackandred) [inline main.go:50]: Having it as []string instead of concatenated string is a form of escaping, by the way.

**Comment by blackandred** [comment]
Tested manually (we need more automatic tests coverage still), it seems it does not break anything, merging.

**Comment by blackandred** [comment]
Related issues in other OSS projects:
https://github.com/open-policy-agent/opa/pull/2421
https://github.com/containers/podman/pull/2582
